<?php if (!defined('ABSPATH')) exit; $settings = get_option('rtce_settings', []); ?>
<div class="rtce-wrap">
    <div class="rtce-header">
        <div>
            <h1>🎟️ Dynamic Coupon Engine</h1>
            <p class="rtce-subtitle">Schedule and automate promotional coupons</p>
        </div>
        <button class="rtce-btn primary" id="rtce-new-promo">+ New Promotion</button>
    </div>

    <div class="rtce-tabs">
        <button class="rtce-tab active" data-tab="promos">Promotions</button>
        <button class="rtce-tab" data-tab="templates">Templates</button>
        <button class="rtce-tab" data-tab="settings">Settings</button>
    </div>

    <!-- Promotions List -->
    <div class="rtce-panel active" id="panel-promos">
        <div class="rtce-stats-grid">
            <div class="rtce-stat-card accent">
                <div class="rtce-stat-num" id="stat-active">—</div>
                <div class="rtce-stat-label">Active</div>
            </div>
            <div class="rtce-stat-card">
                <div class="rtce-stat-num" id="stat-scheduled">—</div>
                <div class="rtce-stat-label">Scheduled</div>
            </div>
            <div class="rtce-stat-card">
                <div class="rtce-stat-num" id="stat-total">—</div>
                <div class="rtce-stat-label">Total Promos</div>
            </div>
            <div class="rtce-stat-card">
                <div class="rtce-stat-num" id="stat-uses">—</div>
                <div class="rtce-stat-label">Total Uses</div>
            </div>
        </div>

        <div id="rtce-promos-list">
            <p class="rtce-muted">Loading promotions...</p>
        </div>
    </div>

    <!-- Templates -->
    <div class="rtce-panel" id="panel-templates">
        <div class="rtce-card">
            <h3>Quick-Start Templates</h3>
            <p class="rtce-hint" style="margin-bottom:20px;">Click a template to pre-fill the promo editor. You can customize everything after.</p>
            <div class="rtce-template-grid" id="rtce-template-grid"></div>
        </div>
    </div>

    <!-- Settings -->
    <div class="rtce-panel" id="panel-settings">
        <form id="rtce-form-settings" class="rtce-form">
            <div class="rtce-card">
                <h3>Banner Settings</h3>
                <div class="rtce-field-row">
                    <div class="rtce-field">
                        <label>Banner Position</label>
                        <select name="banner_position">
                            <option value="top" <?php selected(($settings['banner_position'] ?? 'top'), 'top'); ?>>Top of Page</option>
                            <option value="bottom" <?php selected(($settings['banner_position'] ?? ''), 'bottom'); ?>>Bottom of Page</option>
                        </select>
                    </div>
                    <div class="rtce-field">
                        <label>Font Size (px)</label>
                        <input type="number" name="banner_font_size" value="<?php echo esc_attr($settings['banner_font_size'] ?? 14); ?>" min="10" max="24">
                    </div>
                </div>
                <div class="rtce-check-row">
                    <label><input type="checkbox" name="banner_dismissible" value="1" <?php checked(!empty($settings['banner_dismissible'])); ?>> Allow visitors to dismiss the banner</label>
                </div>
            </div>

            <div class="rtce-card">
                <h3>Coupon Code Settings</h3>
                <div class="rtce-field">
                    <label>Auto-generated Code Prefix</label>
                    <input type="text" name="code_prefix" value="<?php echo esc_attr($settings['code_prefix'] ?? 'RRH'); ?>" maxlength="10">
                    <p class="rtce-hint">Codes will look like: RRH-A3BK9F</p>
                </div>
                <div class="rtce-check-row">
                    <label><input type="checkbox" name="auto_generate_codes" value="1" <?php checked(!empty($settings['auto_generate_codes'])); ?>> Auto-generate codes when left blank</label>
                </div>
                <div class="rtce-check-row">
                    <label><input type="checkbox" name="track_revenue" value="1" <?php checked(!empty($settings['track_revenue'])); ?>> Track revenue generated by coupons</label>
                </div>
            </div>

            <div class="rtce-actions">
                <button type="submit" class="rtce-btn primary">Save Settings</button>
            </div>
        </form>
    </div>

    <!-- Promo Editor Modal -->
    <div class="rtce-modal-overlay" id="rtce-modal">
        <div class="rtce-modal">
            <div class="rtce-modal-header">
                <h2 id="rtce-modal-title">New Promotion</h2>
                <button class="rtce-modal-close" id="rtce-modal-close">✕</button>
            </div>
            <div class="rtce-modal-body">
                <input type="hidden" id="promo-id" value="0">

                <div class="rtce-field">
                    <label>Promotion Name *</label>
                    <input type="text" id="promo-name" placeholder="e.g. Black Friday 2026">
                </div>

                <div class="rtce-field">
                    <label>Description</label>
                    <input type="text" id="promo-description" placeholder="Internal note about this promo">
                </div>

                <div class="rtce-field-row">
                    <div class="rtce-field">
                        <label>Discount Type</label>
                        <select id="promo-discount_type">
                            <option value="percent">Percentage Off</option>
                            <option value="fixed_cart">Fixed $ Off Cart</option>
                            <option value="fixed_product">Fixed $ Off Product</option>
                            <option value="free_shipping">Free Shipping Only</option>
                        </select>
                    </div>
                    <div class="rtce-field" id="promo-value-wrap">
                        <label>Discount Value</label>
                        <input type="number" id="promo-discount_value" step="0.01" min="0" placeholder="e.g. 15">
                    </div>
                </div>

                <div class="rtce-field">
                    <label>Coupon Code (leave blank to auto-generate)</label>
                    <input type="text" id="promo-coupon_code" placeholder="e.g. BLACKFRIDAY25" style="text-transform:uppercase;">
                </div>

                <h4 class="rtce-section-title">📅 Schedule</h4>
                <div class="rtce-field-row">
                    <div class="rtce-field">
                        <label>Start Date</label>
                        <input type="datetime-local" id="promo-start_date">
                    </div>
                    <div class="rtce-field">
                        <label>End Date</label>
                        <input type="datetime-local" id="promo-end_date">
                    </div>
                </div>

                <h4 class="rtce-section-title">📋 Rules</h4>
                <div class="rtce-field-row">
                    <div class="rtce-field">
                        <label>Minimum Cart Total ($)</label>
                        <input type="number" id="promo-min_cart_total" step="0.01" min="0" value="0">
                    </div>
                    <div class="rtce-field">
                        <label>Max Total Uses (0=unlimited)</label>
                        <input type="number" id="promo-max_uses" min="0" value="0">
                    </div>
                    <div class="rtce-field">
                        <label>Max Uses Per Customer</label>
                        <input type="number" id="promo-max_uses_per_user" min="0" value="0">
                    </div>
                </div>
                <div class="rtce-check-row"><label><input type="checkbox" id="promo-first_time_only"> First-time customers only</label></div>
                <div class="rtce-check-row"><label><input type="checkbox" id="promo-free_shipping"> Include free shipping</label></div>
                <div class="rtce-check-row"><label><input type="checkbox" id="promo-exclude_sale_items"> Exclude items already on sale</label></div>
                <div class="rtce-check-row"><label><input type="checkbox" id="promo-auto_apply"> Auto-apply to cart (no code needed)</label></div>

                <h4 class="rtce-section-title">🎯 Targeting</h4>
                <div class="rtce-field">
                    <label>Apply To</label>
                    <select id="promo-apply_to">
                        <option value="all">All Products</option>
                        <option value="categories">Specific Categories</option>
                        <option value="products">Specific Products (IDs)</option>
                    </select>
                </div>
                <div class="rtce-field" id="promo-categories-wrap" style="display:none;">
                    <label>Categories (check to include)</label>
                    <div id="promo-category-checkboxes" class="rtce-checkbox-grid"></div>
                </div>
                <div class="rtce-field" id="promo-products-wrap" style="display:none;">
                    <label>Product IDs (comma-separated)</label>
                    <input type="text" id="promo-product_ids" placeholder="e.g. 123, 456, 789">
                </div>

                <h4 class="rtce-section-title">📢 Announcement Banner</h4>
                <div class="rtce-check-row"><label><input type="checkbox" id="promo-show_banner" checked> Show banner on your store when active</label></div>
                <div class="rtce-field">
                    <label>Banner Text</label>
                    <input type="text" id="promo-banner_text" placeholder="Use {code}, {discount}, {end_date}">
                    <p class="rtce-hint">Variables: {code}, {discount}, {end_date}</p>
                </div>
                <div class="rtce-field-row">
                    <div class="rtce-field">
                        <label>Background Color</label>
                        <input type="color" id="promo-banner_bg_color" value="#A2755A">
                    </div>
                    <div class="rtce-field">
                        <label>Text Color</label>
                        <input type="color" id="promo-banner_text_color" value="#ffffff">
                    </div>
                </div>

                <div class="rtce-banner-preview" id="rtce-banner-preview">
                    <span id="rtce-banner-preview-text">Banner preview...</span>
                </div>
            </div>
            <div class="rtce-modal-footer">
                <select id="promo-status">
                    <option value="draft">Save as Draft</option>
                    <option value="active">Activate Now</option>
                    <option value="scheduled">Schedule (auto-activate on start date)</option>
                </select>
                <button class="rtce-btn primary" id="rtce-save-promo">Save Promotion</button>
            </div>
        </div>
    </div>

    <div class="rtce-toast" id="rtce-toast"></div>
</div>
